version: "3"
services:
  snail-bot:
    command: /snail-bot serve
    build:
      context: ./
    networks:
      - microservices
      - nginx
    env_file:
      - .env
networks:
  microservices:
  nginx:
    external: true
