version: "3"
services:
  snail-bot:
    command: /snail-bot serve
    ports:
      - "8080:8080"
    build:
      context: ./
    networks:
      - microservices
    env_file:
      - .env
networks:
  microservices:
