version: "3"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices
    environment:
      - MYSQL_ROOT_PASSWORD=hogefuga
      - MYSQL_DATABASE=snail_bot
      - MYSQL_USER=snailbot
      - MYSQL_PASSWORD=botdatabase
      - TZ=Asia/Tokyo
volumes:
  mysql-data:
networks:
  microservices:
