version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "89:be:af:57:88:c7:78:27:a4:de:6e:db:03:c0:17:cc"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "~/deploy-script/deploy --build --restart -s snail-bot -f docker-compose.prod.yaml"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master